### ISSUE TITLE
Fonts we fail to parse: reEndMarker doesn't match: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by stefanor** [pwaller/pyfiglet#116] opened 2023-08-11 11:16 UTC
The zip fonts and some others fail to parse:

e.g. for `ascii12`:
```
Traceback (most recent call last):
  File "pyfiglet/__init__.py", line 349, in loadFont
    width, letter = __char(data)
                    ^^^^^^^^^^^^
  File "pyfiglet/__init__.py", line 316, in __char
    end = self.reEndMarker.search(line).group(1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

This applies to:

* ascii12
* ascii9
* bigascii12
* bigascii9
* bigmono12
* bigmono9
* dwhistled
* gradient
* mono12
* mono9
* smascii12
* smascii9
* smmono12
* smmono9

They're currently (as of #115) skipped in the tests.

**Comment by peterbrittain** [comment] 2023-08-20 09:46
Just had a look at this.  The problem is that python has a better unicode implementation than toilet/figlet.

In particular, it recognises more line ending characters than the simple CRLF of days gone by.  See here for full list of separators: https://github.com/python/cpython/blob/b1e5d2c601bbd3d435b60deef4818f3622bdfca3/Objects/unicodetype_db.h#L6355

The fix is going to need to spot and remove these rogue characters (e.g. when used in extended character definitions).

**Comment by peterbrittain** [comment] 2023-08-23 07:13
You can close this one now.

**Comment by pwaller** [comment] 2023-08-23 07:17
Thanks @peterbrittain, I've added you as a collaborator to the repository so you should have the power to close it now.

**Closed** 2023-08-23 07:20 UTC
Labels: help wanted
